
name: aws-nonauto-scale
label: AWS Non-AutoScale
description: AWS Full Environment from
type: terraform
extends:

# Note the variable names should match between variables.tf and .meta-cnc.yaml
#WebCIDR_UntrustBlock1 = "10.0.1.0/24"
#WebCIDR_TrustBlock2 = "10.0.12.0/24"
#WebCIDR_UntrustBlock2 = "10.0.11.0/24"
#WebCIDR_MGMT1 = "10.0.0.0/24"
#WebCIDR_MGMT2 = "10.0.10.0/24"
#VPCName = "vv-2t-vpc"
#WebSRV1_AZ1_Trust = "10.0.2.50"
#WebSRV2_AZ2_Trust = "10.0.12.50"
#FW1_Untrust_IP = "10.0.1.10"
#FW1_Trust_IP = "10.0.2.10"
#FW1_mgmt_IP = "10.0.0.10"
#FW2_Untrust_IP = "10.0.11.10"
#FW2_Trust_IP = "10.0.12.10"
#FW2_mgmt_IP = "10.0.10.10"
#StackName = "vv-2t"
#VPCCIDR = "10.0.0.0/16"
#aws_region = "Place Region Here"
#ServerKeyName = "Place Keypair Here"
#MasterS3Bucket = "Place S3 Bucket Here"
#aws_access_key = "Place Access Key Here"
#aws_secret_key = "Place Secret Key Here"

labels:
  service_type: aws_terraform

variables:
  - name: aws_access_key
    description: AWS Access Key
    default: Place your Access Key
    type_hint: text
  - name: aws_secret_key
    description: AWS Secret Key
    default:
    type_hint: password
  - name: ServerKeyName
    description: SSH Key Name
    default: ssh_key_pair
    type_hint: text
  - name: aws_region
    description: AWS Region
    default: us-east-2
    type_hint: text
  - name: MasterS3Bucket
    description: Bootstrap S3 Bucket Name
    default: s3-something
    type_hint: text

