variable "mgt-ipaddress-fw1" {}
variable "untrust-ipaddress-fw1" {}
variable "mgt-ipaddress-fw2" {}
variable "untrust-ipaddress-fw2" {}
variable "WebSrv1_IP" {}
variable "WebSrv2_IP" {}
variable "int-nlb-fqdn" {}
variable "username" {}
variable "password" {}
